function onOpen() {
  const ui = SpreadsheetApp.getUi();
  ui.createMenu('Voice Note App')
    .addSubMenu(ui.createMenu('Setup')
      .addItem('Initialize project (folders + EN prompts)', 'vnaInitProjectFromSheet')
      .addSeparator()
      .addItem('Sync Sheet → Script Properties', 'vnaSyncPropsFromSheet')
      .addItem('Sync Script Properties → Sheet', 'vnaSyncSheetFromProps')
      .addSeparator()
      .addItem('Test OpenAI Key', 'vnaTestOpenAIKey'))
    .addSubMenu(ui.createMenu('Triggers')
      .addItem('Create Hourly trigger', 'createHourlyWorkerTrigger')
      .addItem('Create Daily trigger', 'createDailyTrigger')
      .addItem('Create Weekly trigger', 'createWeeklyTrigger')
      .addSeparator()
      .addItem('Create ALL triggers', 'createAllTriggers'))
    .addSubMenu(ui.createMenu('Run now')
      .addItem('Run Hourly worker now', 'hourlyTranscriptionWorker')
      .addItem('Run Daily now', 'main')
      .addItem('Run Weekly now', 'weeklyMain')
      .addItem('Run Monthly now', 'monthlyMain_'))
    .addSubMenu(ui.createMenu('Open folders')
      .addItem('Open Root (Voice Note App)', 'vnaOpenRootFolder')
      .addItem('Open Source Audio', 'vnaOpenSourceAudio')
      .addItem('Open Transcriptions', 'vnaOpenTranscriptions')
      .addItem('Open Audio Archive', 'vnaOpenArchive')
      .addSeparator()
      .addItem('Open Daily Summaries', 'vnaOpenDaily')
      .addItem('Open Weekly Summaries', 'vnaOpenWeekly')
      .addItem('Open Monthly Summaries', 'vnaOpenMonthly')
      .addSeparator()
      .addItem('Open Prompts (EN)', 'vnaOpenPromptsEn'))
    .addToUi();
}
